title: Samizo-AITL
description: Technical Portfolio by Shinichi Samizo
theme: minima
lang: ja

# ✅ 手動ナビゲーション設定（自動リンクを抑制）
header_pages:
  - index.md
  - en/index.md

# ✅ 投稿記事の概要など不要な表示を抑制（minimaの仕様対策）
show_excerpts: false

# ✅ GitHub Pagesでは以下を有効にすることで Jekyll を正しく動作させる
markdown: kramdown
kramdown:
  input: GFM

# ✅ Sass（SCSS）対応を有効化（CSS変換のため）
sass:
  style: compressed  # or "expanded" for読みやすさ優先

# ✅ baseurlやurlは後で使うならアンコメント
# url: "https://samizo-aitl.github.io"
# baseurl: ""

# ✅ 将来的にexclude設定する場合
# exclude:
#   - README.md
#   - LICENSE
#   - docs/
